### ISSUE TITLE
When I run the YOLO_pred.py, there is an error " Using a `tf.Tensor` as a Python `bool` is not allowed. "

### ISSUE THREAD

**Issue by zzuxzt** [qjadud1994/YOLOv2-keras#2]
Traceback (most recent call last):
  File "YOLO_pred.py", line 15, in <module>
    yolo_output = multi_yolo(darknet)
  File "/home/xzt/DeepEye/YOLOv2-keras/Model.py", line 181, in multi_yolo
    final = Reshape([shape[1], shape[2], 5, CLASS + BOX], name="final_reshape")(x)
  File "/home/xzt/anaconda3/envs/Yv2-k/lib/python3.5/site-packages/keras/engine/topology.py", line 636, in __call__
    output_shape = self.compute_output_shape(input_shape)
  File "/home/xzt/anaconda3/envs/Yv2-k/lib/python3.5/site-packages/keras/layers/core.py", line 402, in compute_output_shape
    input_shape[1:], self.target_shape)
  File "/home/xzt/anaconda3/envs/Yv2-k/lib/python3.5/site-packages/keras/layers/core.py", line 376, in _fix_unknown_dimension
    if dim < 0:
  File "/home/xzt/anaconda3/envs/Yv2-k/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 606, in __bool__
    raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.

**Comment by zhangyufei1995** [comment]
same issue,have you solved the question?

**Comment by zzuxzt** [comment]
My error is caused by different python versions. Please check the python version you used to convert yolo model and that you used to run YOLO_pred.py.
